services:
  - type: web
    name: documind-web
    runtime: docker
    repo: https://github.com/dnpuneeth/personal-ai-projects
    branch: main
    autoDeploy: true
    dockerfilePath: apps/documind/api/Dockerfile
    dockerContext: apps/documind/api
    healthCheckPath: /healthz
    plan: free
    startCommand: ./bin/thrust ./bin/rails server -b 0.0.0.0 -p $PORT
    preDeployCommand: bundle exec rails db:migrate
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: documind-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: documind-redis
          type: redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: LLM_MODEL
        value: gpt-4o-mini
      - key: S3_BUCKET
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: OTEL_EXPORTER_OTLP_ENDPOINT
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false

  - type: worker
    name: documind-worker
    runtime: docker
    repo: https://github.com/dnpuneeth/personal-ai-projects
    branch: main
    autoDeploy: true
    dockerfilePath: apps/documind/api/Dockerfile
    dockerContext: apps/documind/api
    plan: free
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: documind-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: documind-redis
          type: redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: LLM_MODEL
        value: gpt-4o-mini
      - key: S3_BUCKET
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: OTEL_EXPORTER_OTLP_ENDPOINT
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: documind-redis
    plan: free
    ipAllowList: []

databases:
  - name: documind-db
    plan: starter
    databaseName: documind
    user: documind
