---
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5).to_i %>
:queues:
  - [default, 1]
  - [mailers, 1]
  - [active_storage, 1]
  - [ai_processing, 2]
  - [document_processing, 3]

:max_retries: 3
:retry_interval: 5

# Redis configuration is handled in config/initializers/sidekiq.rb
# This file is for queue-specific settings only

# Logging
:logfile: STDOUT
:loglevel: INFO

# Process monitoring
:pidfile: tmp/pids/sidekiq.pid
