name: Deploy DocuMind

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.4'
        bundler-cache: true

    - name: Install Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      run: |
        cd apps/documind/api
        flyctl deploy --config ../../../infra/fly.documind.toml --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Run database migrations
      run: |
        cd apps/documind/api
        flyctl ssh console -C "bundle exec rails db:migrate"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Health check
      run: |
        cd apps/documind/api
        flyctl status
        # Wait for app to be ready
        sleep 30
        # Test health endpoint
        curl -f https://documind.fly.dev/healthz
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 